---
- name: Install GPU Operator
  hosts: localhost
  become: true 
  vars:
    gpu_operator_namespace: "nvidia-gpu-operator"
    gpu_operator_values_file: "/tmp/gpu-operator-values.yaml"

  tasks:
    - name: Ensure GPU Operator namespace exists
      shell: |
        kubectl get ns {{ gpu_operator_namespace }} || kubectl create ns {{ gpu_operator_namespace }}

    - name: Add Helm repos
      shell: |
        helm repo add nvidia https://helm.ngc.nvidia.com/nvidia || true
        helm repo update

    # GPU Operator customization: ensure DCGM Exporter port is named 'metrics' and labeled correctly
    - name: Write GPU Operator values.yaml
      copy:
        dest: "{{ gpu_operator_values_file }}"
        content: |
          dcgmExporter:
            service:
              labels:
                app: dcgm-exporter
              ports:
                - name: gpu-metrics
                  port: "9400"
                  targetPort: "9400"

    - name: Install GPU Operator via Helm
      shell: |
        helm upgrade --install gpu-operator nvidia/gpu-operator \
          --namespace {{ gpu_operator_namespace }} \
          -f {{ gpu_operator_values_file }}
