---
- name: Copy kubeconfig from root and configure kubectl auto-completion
  hosts: kube_control_plane 
  become: no 
  tasks:
    - name: Copy kubeconfig
      ansible.builtin.shell: |
        sudo mkdir -p ~/.kube
        sudo cp /root/.kube/config ~/.kube/
        sudo chown $(id -u):$(id -g) ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Install bash-completion
      apt:
        name: bash-completion
        state: present

    - name: Configure kubectl auto-completion 
      ansible.builtin.shell: |
        kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
        echo 'alias k=kubectl' >>~/.bashrc
        echo 'complete -o default -F __start_kubectl k' >>~/.bashrc
